[tox]
env_list = lint, typecheck, test

[testenv]
basepython = python3.12

[testenv:lint]
deps = ruff
commands = ruff check src/ test/

[testenv:typecheck]
deps =
    pyright
    {[testenv:test]deps}
commands = pyright src/

[testenv:test]
deps =
    pytest
    -e .
commands = pytest {posargs}
