[tox]
envlist = lint, typecheck, test
isolated_build = true

[testenv]
base_python = python3.12
extras = dev

[testenv:lint]
deps = ruff
commands = ruff check src test

[testenv:typecheck]
deps = pyright
extras = dev
commands = pyright src test

[testenv:test]
deps =
    pytest
    pytest-httpx
extras = dev
commands = pytest test -v
