[tox]
envlist = lint, typecheck, test
isolated_build = true

[testenv]
basepython = python3.12

[testenv:lint]
deps = ruff
commands = ruff check src/

[testenv:typecheck]
deps =
    pyright
    pydantic
    pydantic-settings
    fastapi
    httpx
    peewee
    pandas-stubs
    numpy
commands = pyright src/

[testenv:test]
deps = pytest
commands = pytest
